[package]
name = "jsc_bindgen"
version = "0.1.0"
authors = ["Leonardo Bartoloni <leonardo@biobeats.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[build-dependencies]
bindgen = "0.54.0"
pkg-config = "0.3.17"